// <auto-generated />
using AutoSalon.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace AutoSalon.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20181225090256_pocetna")]
    partial class pocetna
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AutoSalon.Models.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("UserID");

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("User");
                });

            modelBuilder.Entity("AutoSalon.Models.AutoDetalji", b =>
                {
                    b.Property<int>("AutomobilID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cijena");

                    b.Property<string>("EmisioniStandard");

                    b.Property<string>("Gorivo");

                    b.Property<string>("Kilometraza");

                    b.Property<string>("Kilovati");

                    b.Property<string>("KonjskeSnage");

                    b.Property<string>("Kubikaza");

                    b.Property<string>("Pogon");

                    b.Property<string>("Tezina");

                    b.Property<string>("Tip");

                    b.Property<string>("Transmisija");

                    b.Property<string>("VelicinaFelgi");

                    b.Property<string>("brojBrzina");

                    b.Property<string>("brojSjedista");

                    b.Property<string>("brojVrata");

                    b.Property<string>("cijenaRentanja");

                    b.HasKey("AutomobilID");

                    b.ToTable("Autodetalji");
                });

            modelBuilder.Entity("AutoSalon.Models.Automobil", b =>
                {
                    b.Property<int>("AutomobilID");

                    b.Property<string>("Boja");

                    b.Property<bool>("Dostupan");

                    b.Property<string>("GodinaProizvodnje");

                    b.Property<string>("Model");

                    b.Property<bool>("Novo");

                    b.Property<int>("ProizvodjacID");

                    b.Property<string>("Slika");

                    b.HasKey("AutomobilID");

                    b.HasIndex("ProizvodjacID");

                    b.ToTable("Automobili");
                });

            modelBuilder.Entity("Autosalon.Models.DodatnaOprema", b =>
                {
                    b.Property<int>("DodatnaOpremaID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Naziv");

                    b.HasKey("DodatnaOpremaID");

                    b.ToTable("DodatneOpreme");
                });

            modelBuilder.Entity("AutoSalon.Models.Drzava", b =>
                {
                    b.Property<int>("DrzavaID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Naziv");

                    b.HasKey("DrzavaID");

                    b.ToTable("Drzave");
                });

            modelBuilder.Entity("AutoSalon.Models.Grad", b =>
                {
                    b.Property<int>("GradID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DrzavaID");

                    b.Property<string>("Naziv");

                    b.Property<string>("PostanskiBroj");

                    b.HasKey("GradID");

                    b.HasIndex("DrzavaID");

                    b.ToTable("Gradovi");
                });

            modelBuilder.Entity("AutoSalon.Models.Kupovina", b =>
                {
                    b.Property<int>("KupovinaID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AutomobilID");

                    b.Property<DateTime>("DatumKupovine");

                    b.Property<double>("Iznos");

                    b.Property<int>("KlijentID");

                    b.Property<string>("Opis");

                    b.Property<int>("PoslovnicaID");

                    b.Property<int>("RacunID");

                    b.Property<int>("UposlenikID");

                    b.HasKey("KupovinaID");

                    b.HasIndex("AutomobilID");

                    b.HasIndex("KlijentID");

                    b.HasIndex("PoslovnicaID");

                    b.HasIndex("RacunID");

                    b.HasIndex("UposlenikID");

                    b.ToTable("Kupovine");
                });

            modelBuilder.Entity("Autosalon.Models.Ocjena", b =>
                {
                    b.Property<int>("RezervacijaRentanjaID");

                    b.Property<DateTime>("DatumEvidentiranja");

                    b.Property<string>("Napomena");

                    b.Property<int>("ocjena");

                    b.HasKey("RezervacijaRentanjaID");

                    b.ToTable("Ocjene");
                });

            modelBuilder.Entity("AutoSalon.Models.Poslovnica", b =>
                {
                    b.Property<int>("PoslovnicaID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Adresa")
                        .HasMaxLength(30);

                    b.Property<int>("GradID");

                    b.Property<string>("KontaktTelefon");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("SlikaURL");

                    b.HasKey("PoslovnicaID");

                    b.HasIndex("GradID");

                    b.ToTable("Poslovnice");
                });

            modelBuilder.Entity("AutoSalon.Models.Proizvodjac", b =>
                {
                    b.Property<int>("ProizvodjacID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DrzavaID");

                    b.Property<string>("Naziv");

                    b.HasKey("ProizvodjacID");

                    b.HasIndex("DrzavaID");

                    b.ToTable("Proizvodjaci");
                });

            modelBuilder.Entity("AutoSalon.Models.Racun", b =>
                {
                    b.Property<int>("RacunID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DatumIzdavanja");

                    b.Property<float>("Iznos");

                    b.HasKey("RacunID");

                    b.ToTable("Racuni");
                });

            modelBuilder.Entity("Autosalon.Models.RezervacijaRentanje", b =>
                {
                    b.Property<int>("RezervacijaRentanjaID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AutomobilID");

                    b.Property<DateTime>("DatumKreiranja");

                    b.Property<double>("Iznos");

                    b.Property<int>("KlijentID");

                    b.Property<string>("Opis");

                    b.Property<double>("Popust");

                    b.Property<int>("PoslovnicaID");

                    b.Property<int?>("RacunID");

                    b.Property<DateTime>("RezervacijaDo");

                    b.Property<DateTime>("RezervacijaOd");

                    b.Property<int>("UposlenikID");

                    b.HasKey("RezervacijaRentanjaID");

                    b.HasIndex("AutomobilID");

                    b.HasIndex("KlijentID");

                    b.HasIndex("PoslovnicaID");

                    b.HasIndex("RacunID");

                    b.HasIndex("UposlenikID");

                    b.ToTable("rezervacijeRentanja");
                });

            modelBuilder.Entity("Autosalon.Models.RezervacijaTestiranje", b =>
                {
                    b.Property<int>("RezervacijaTestiranjaID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AutomobilID");

                    b.Property<DateTime>("DatumKreiranja");

                    b.Property<DateTime>("DatumTestiranja");

                    b.Property<int>("KlijentID");

                    b.Property<int>("PoslovnicaID");

                    b.Property<string>("Status");

                    b.Property<int>("UposlenikID");

                    b.HasKey("RezervacijaTestiranjaID");

                    b.HasIndex("AutomobilID");

                    b.HasIndex("KlijentID");

                    b.HasIndex("PoslovnicaID");

                    b.HasIndex("UposlenikID");

                    b.ToTable("rezervacijeTestiranja");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RoleID");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RoleClaimID");

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<int>("RoleId")
                        .HasColumnName("RoleID");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaim");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("UserClaimID");

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<int>("UserId")
                        .HasColumnName("UserID");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaim");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<int>("UserId")
                        .HasColumnName("UserID");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogin");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnName("UserID");

                    b.Property<int>("RoleId")
                        .HasColumnName("RoleID");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnName("UserID");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserToken");
                });

            modelBuilder.Entity("AutoSalon.Models.Automobil", b =>
                {
                    b.HasOne("AutoSalon.Models.AutoDetalji", "AutoDetalji")
                        .WithOne("Automobil")
                        .HasForeignKey("AutoSalon.Models.Automobil", "AutomobilID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AutoSalon.Models.Proizvodjac", "Proizvodjac")
                        .WithMany()
                        .HasForeignKey("ProizvodjacID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AutoSalon.Models.Grad", b =>
                {
                    b.HasOne("AutoSalon.Models.Drzava", "Drzava")
                        .WithMany()
                        .HasForeignKey("DrzavaID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AutoSalon.Models.Kupovina", b =>
                {
                    b.HasOne("AutoSalon.Models.Automobil", "Automobil")
                        .WithMany()
                        .HasForeignKey("AutomobilID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AutoSalon.Models.ApplicationUser", "Klijent")
                        .WithMany()
                        .HasForeignKey("KlijentID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AutoSalon.Models.Poslovnica", "Poslovnica")
                        .WithMany()
                        .HasForeignKey("PoslovnicaID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AutoSalon.Models.Racun", "Racun")
                        .WithMany()
                        .HasForeignKey("RacunID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AutoSalon.Models.ApplicationUser", "Uposlenik")
                        .WithMany()
                        .HasForeignKey("UposlenikID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Autosalon.Models.Ocjena", b =>
                {
                    b.HasOne("Autosalon.Models.RezervacijaRentanje", "RezervacijaRentanja")
                        .WithOne("Ocjena")
                        .HasForeignKey("Autosalon.Models.Ocjena", "RezervacijaRentanjaID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AutoSalon.Models.Poslovnica", b =>
                {
                    b.HasOne("AutoSalon.Models.Grad", "Grad")
                        .WithMany()
                        .HasForeignKey("GradID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AutoSalon.Models.Proizvodjac", b =>
                {
                    b.HasOne("AutoSalon.Models.Drzava", "Drzava")
                        .WithMany()
                        .HasForeignKey("DrzavaID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Autosalon.Models.RezervacijaRentanje", b =>
                {
                    b.HasOne("AutoSalon.Models.Automobil", "Automobil")
                        .WithMany()
                        .HasForeignKey("AutomobilID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AutoSalon.Models.ApplicationUser", "Klijent")
                        .WithMany()
                        .HasForeignKey("KlijentID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AutoSalon.Models.Poslovnica", "Poslovnica")
                        .WithMany()
                        .HasForeignKey("PoslovnicaID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AutoSalon.Models.Racun", "Racun")
                        .WithMany()
                        .HasForeignKey("RacunID");

                    b.HasOne("AutoSalon.Models.ApplicationUser", "Uposlenik")
                        .WithMany()
                        .HasForeignKey("UposlenikID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Autosalon.Models.RezervacijaTestiranje", b =>
                {
                    b.HasOne("AutoSalon.Models.Automobil", "Automobil")
                        .WithMany()
                        .HasForeignKey("AutomobilID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AutoSalon.Models.ApplicationUser", "Klijent")
                        .WithMany()
                        .HasForeignKey("KlijentID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AutoSalon.Models.Poslovnica", "Poslovnica")
                        .WithMany()
                        .HasForeignKey("PoslovnicaID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AutoSalon.Models.ApplicationUser", "Uposlenik")
                        .WithMany()
                        .HasForeignKey("UposlenikID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("AutoSalon.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("AutoSalon.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AutoSalon.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("AutoSalon.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
